# Generated by Django 4.2.1 on 2023-05-16 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Viajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='fecha_viaje',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ingrese la fecha de viaje'),
        ),
    ]
