# Generated by Django 4.2.1 on 2023-05-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Viajes', '0002_alter_viaje_fecha_viaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoViajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivoviajes', models.CharField(max_length=100, verbose_name='Ingrese el motivo por lo caual Viaja')),
            ],
            options={
                'verbose_name': 'motivo Viajes',
                'verbose_name_plural': 'motivo Viajes',
            },
        ),
    ]
