# Generated by Django 4.2.1 on 2023-05-17 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Viajes', '0003_motivoviajes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViajeMotivoViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivoViaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Viajes.motivoviajes')),
                ('viaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Viajes.viaje')),
            ],
            options={
                'verbose_name': 'ViajeMotivoViaje',
                'verbose_name_plural': ' ViajesMotivosViajes',
            },
        ),
        migrations.AddField(
            model_name='viaje',
            name='motivoViaje',
            field=models.ManyToManyField(through='Viajes.ViajeMotivoViaje', to='Viajes.motivoviajes', verbose_name='ViajeMotivoViaje'),
        ),
    ]
